version: '3.8'

services:
  app:
    build: .
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"  # Frontend
      - "${BACKEND_PORT:-3002}:${BACKEND_PORT:-3002}"  # Backend
    environment:
      - NODE_ENV=production
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - BACKEND_PORT=${BACKEND_PORT:-3002}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped 